import { StyleSheet } from 'react-native';
import { Colors, Radii } from '../../config/theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  kav: {
    width: '100%',
  },
  sheet: {
    backgroundColor: Colors.bgSurface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.border,
    alignSelf: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: Colors.textPrimary,
    marginBottom: 16,
  },
  customerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  customerAvatar: {
    width: 44,
    height: 44,
    borderRadius: Radii.pill,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customerAvatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.primary,
  },
  customerDetails: {
    flex: 1,
  },
  customerName: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  customerBranch: {
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  debtInfoBox: {
    backgroundColor: Colors.warningLight,
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: Radii.md,
    padding: 14,
    marginBottom: 16,
  },
  debtInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  debtInfoItem: {
    gap: 2,
  },
  debtInfoLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: Colors.warning,
  },
  debtInfoAmount: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.warning,
  },
  debtInfoLabelDanger: {
    fontSize: 11,
    fontWeight: '500',
    color: Colors.danger,
  },
  debtInfoAmountDanger: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.danger,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  methodRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  methodBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: Radii.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgSurface,
  },
  methodBtnActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  methodBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  methodBtnTextActive: {
    color: '#FFFFFF',
  },
  amountInput: {
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: Radii.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 22,
    fontWeight: '800',
    color: Colors.textPrimary,
    backgroundColor: Colors.bgSubtle,
    marginBottom: 10,
    textAlign: 'center',
  },
  quickFillRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  quickFillBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: Radii.pill,
    backgroundColor: Colors.primaryLight,
  },
  quickFillText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.primary,
  },
  noteInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radii.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: Colors.textPrimary,
    backgroundColor: Colors.bgSubtle,
    marginBottom: 20,
    textAlignVertical: 'top',
    minHeight: 50,
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radii.md,
    paddingVertical: 14,
    alignItems: 'center',
  },
  cancelBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  payBtn: {
    flex: 2,
    flexDirection: 'row',
    backgroundColor: Colors.success,
    borderRadius: Radii.md,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: Colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  btnDisabled: {
    opacity: 0.6,
  },
  payBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
