import { StyleSheet } from 'react-native';

// ─── Constants ────────────────────────────────────────────────────────────────

export const C = {
  bg:      '#F9FAFB',
  white:   '#FFFFFF',
  text:    '#111827',
  muted:   '#9CA3AF',
  border:  '#E5E7EB',
  primary: '#2563EB',
  green:   '#16A34A',
} as const;

// ─── Styles ───────────────────────────────────────────────────────────────────

export const styles = StyleSheet.create({
  safe:    { flex: 1, backgroundColor: C.bg },
  loader:  { flex: 1 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: C.white,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  backBtn:       { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', marginLeft: -8 },
  headerTitle:   { flex: 1, fontSize: 18, fontWeight: '700', color: C.text, textAlign: 'center' },
  headerSpacer:  { width: 40 },
  addBtn:        { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },

  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    backgroundColor: C.white,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  filterChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
  },
  filterChipActive:  { backgroundColor: '#EFF6FF', borderColor: C.primary },
  filterLabel:       { fontSize: 12, fontWeight: '600', color: C.muted },
  filterLabelActive: { color: C.primary },
  filterCount:       { fontSize: 13, fontWeight: '800', color: C.text },
  filterCountActive: { color: C.primary },

  listContent: { padding: 16, paddingBottom: 32 },
  separator:   { height: 10 },

  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    gap: 12,
  },
  typeBadgeCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeBadgeText:  { fontSize: 14, fontWeight: '800' },
  cardBody:       { flex: 1, gap: 4 },
  cardRow:        { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardName:       { flex: 1, fontSize: 15, fontWeight: '700', color: C.text },
  cardValue:      { fontSize: 14, fontWeight: '600', color: C.text },
  cardDate:       { fontSize: 12, color: C.muted },

  statusBadge:       { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 20 },
  statusActive:      { backgroundColor: '#D1FAE5' },
  statusEnded:       { backgroundColor: '#F3F4F6' },
  statusText:        { fontSize: 11, fontWeight: '700' },
  statusActiveText:  { color: C.green },
  statusEndedText:   { color: C.muted },

  // Modal
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.4)' },
  modalSheet: {
    backgroundColor: C.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 12,
    maxHeight: '90%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.border,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTitle:   { fontSize: 18, fontWeight: '700', color: C.text, marginBottom: 20 },
  fieldLabel:   { fontSize: 13, fontWeight: '600', color: C.text, marginBottom: 6, marginTop: 12 },
  input: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: C.text,
    backgroundColor: C.bg,
  },
  toggleRow: { flexDirection: 'row', gap: 8 },
  toggleBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    backgroundColor: C.bg,
  },
  toggleBtnActive:  { backgroundColor: '#EFF6FF', borderColor: C.primary },
  toggleText:       { fontSize: 14, fontWeight: '600', color: C.muted },
  toggleTextActive: { color: C.primary },

  modalActions: { flexDirection: 'row', gap: 12, marginTop: 24 },
  cancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
  },
  cancelBtnText: { fontSize: 15, fontWeight: '600', color: C.text },
  saveBtn: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: C.primary,
    alignItems: 'center',
  },
  saveBtnDisabled: { backgroundColor: C.muted },
  saveBtnText:     { fontSize: 15, fontWeight: '700', color: C.white },
});
